# FROM node:12-alpine
# WORKDIR /app
# COPY .next ./.next
# COPY package.json ./package.json
# RUN yarn
# CMD yarn next start -p $PORT

FROM node:16-alpine
WORKDIR /usr/src/app
COPY package.json ./
RUN npm install -f
COPY . ./
EXPOSE 9090
CMD [ "node", "main.js" ]